package com.oldboy.tasks.Lesson2.Sequences.InterfaceAndClasses;

public interface Sequences {
    void seqA(int n); // X1 = 2; X2 = 4; X(n) = X(n-1) + 2 ...
    void seqB(int n); // X1 = 1; X2 = 3; X(n) = X(n-1) + 2 ...
    void seqC(int n); // X1 = 1; X2 = 4; X(n) = n * n ...
    void seqD(int n); // X1 = 1; X2 = 8; X(n) = n * n * n ...
    void seqE(int n); // X1 = 1; X2 = -1; X(n%2 != 0) = 1; X(n%2 == 0) = -1 ...
    void seqF(int n); // X1 = 1; X2 = -2; X(n%2 != 0) = n; X(n%2 == 0) = -n ...
    void seqG(int n); // X1 = 1; X2 = -4; X(n%2 != 0) = (n * n); X(n%2 == 0) = -(n * n) ...
    void seqH(int n); // X1 = 1; X2 = 0; X(n%2 != 0) = (n - 1)/2 + 1; X(n%2 == 0) = 0 ...
    void seqI(int n); // X1 = 1; X2 = 2; X(n) = X(n - 1) * n ...
    void seqJ(int n); // X1 = 1; X2 = 1; X3 = 2; X(n) = X(n - 1) + X(n - 2) ...
}
